export const CATEGORIES = ['all', 'portrait', 'street', 'nature', 'abstract'];
export const PHOTOS = [
    {
        id: '1',
        src: 'photos/1.jpg',
        alt: 'Portrait',
        category: 'portrait',
        title: 'Still',
        year: 2025,
        orientation: 'portrait',
    },
    {
        id: '2',
        src: 'photos/2.jpg',
        alt: 'Street',
        category: 'street',
        title: 'The Walk',
        year: 2025,
        orientation: 'landscape',
    },
    {
        id: '3',
        src: 'photos/3.jpg',
        alt: 'Nature',
        category: 'nature',
        title: 'Open',
        year: 2025,
        orientation: 'landscape',
    },
    {
        id: '4',
        src: 'photos/4.JPG',
        alt: 'Landscape',
        category: 'nature',
        title: 'Wide',
        year: 2025,
        orientation: 'landscape',
    },
    {
        id: '5',
        src: 'photos/5.JPG',
        alt: 'Abstract',
        category: 'abstract',
        title: 'Light',
        year: 2025,
        orientation: 'landscape',
    },
    {
        id: '6',
        src: 'photos/6.jpg',
        alt: 'Portrait',
        category: 'portrait',
        title: 'Gaze',
        year: 2025,
        orientation: 'portrait',
    },
    {
        id: '7',
        src: 'photos/7.jpg',
        alt: 'Portrait',
        category: 'portrait',
        title: 'Presence',
        year: 2025,
        orientation: 'portrait',
    },
];
